# Generated by Django 5.0.1 on 2024-02-25 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('show_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurementitem',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
