# Generated by Django 5.0.1 on 2024-02-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adddevices',
            name='device_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
