# Generated by Django 5.0.1 on 2024-02-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_measurementitem_deviceid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementitem',
            name='deviceId',
        ),
        migrations.AddField(
            model_name='measurementitem',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
