# Generated by Django 5.0.1 on 2024-02-25 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_measurementitem_deviceid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='device3',
        ),
        migrations.DeleteModel(
            name='MeasurementItem',
        ),
        migrations.DeleteModel(
            name='NewItem',
        ),
    ]
